=== quanpands/wflow/pcraster/pcraster-4.2.0/pcraster-4.2.0/source/pcraster_model_engine/testlist.dtd
<!-- DTD test description
     internal DTD to create and verify tests
  -->

<!-- start copy section from libs/pcrxml/pcraster.dtd -->

<!ENTITY testPublic  PUBLIC "-//PCRaster//DTD PCRasterInternal V1.0//EN" "http://www.pcraster.nl">


<!--
<!ENTITY % String 'CDATA' >
<!ENTITY % Boolean         '(true|false)'>

<!ENTITY % DataTypeEnum '(Unknown|Boolean|Nominal|Ordinal|Scalar|Directional|Ldd|1|4|f)'>
<!ELEMENT  DataType EMPTY>
<!ATTLIST  DataType
           value %DataTypeEnum; #REQUIRED>
-->
<!-- end copy section from libs/pcrxml/pcraster.dtd -->

<!ELEMENT  testlist (test*,makefile) >
<!ELEMENT  test     ((ast|model)?,(result|msg)?) >
<!ELEMENT  makefile  ANY>
<!ATTLIST  test
           id   ID #REQUIRED>

<!-- message/result
     illnamed: result is a better name
     resFile  create a textfile named "<id>.res"
              within testdir
     replace  if yes comparing msg should be done
              after a number of replacement for possible platform
              specifics:
              LicensedFeatures::filePath() => @LF
              \ => X
              / => X
              NOTE both style of slashes are done, set up tests
                   accordingly
              see calc_messagestestdb.cc at:
              if (e.hasAttribute("replace")) {
                 ...
              }
  -->
<!ELEMENT  msg     (#PCDATA)>
<!ATTLIST  msg
           resFile (yes) #IMPLIED
           replace (yes) #IMPLIED>
<!-- result,
     nog uitwerken, numeric kaart
     etc.
  -->
<!ELEMENT  result  (#PCDATA)>

<!ENTITY % ExprTypes 'e|n|p'>
<!ENTITY % NodeTypes 'l|a|e|n|p'>

<!ELEMENT  ast    (%NodeTypes;)>

<!ELEMENT  model   (#PCDATA)>
<!ATTLIST  model
           options  CDATA #IMPLIED>

<!ENTITY % Value 'v CDATA #REQUIRED'>
<!ENTITY % Pos   'p CDATA #IMPLIED'>

<!-- list of statements -->
<!ELEMENT  l      (%NodeTypes;)+>

<!--
   assignment  par=expr
   <a v='par'><e ..expr..></a>
-->
<!ELEMENT  a      (%ExprTypes;)*>
<!-- Value is the assigned par -->
<!ATTLIST  a
              %Value;
              %Pos;  >

<!--
     expression
 -->
<!ELEMENT  e      (%ExprTypes;)*>
<!--
     a                  ,-seperated arg list
 -->
<!ATTLIST  e
  a                  CDATA #IMPLIED
  %Value;
  %Pos;  >

<!ELEMENT  n      EMPTY>
<!ATTLIST  n
              %Value;
              %Pos;  >
<!ELEMENT  p      EMPTY>
<!ATTLIST  p
              %Value;
              %Pos;  >

=== quanpands/wflow/pcraster/pcraster-4.2.0/pcraster-4.2.0/source/pcraster_model_engine/messagestest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testlist 
PUBLIC "-//PCRaster//DTD PCRasterInternal V1.0//EN" "testlist.dtd"
[ <!-- NA NEE, momenteel geen expand entities -->
 <!ENTITY Clone " --clone inp5s.map "
 >
]
>

<!-- list of messages as expected 
     pcrcalcXXX refers to test number in 
      $OLDPCRTREE/test/pcrcalc/testXXX

      XXX >= 500 new tests
      pcrcalc561 is last used

     contents of msg ignores trailing and leading whitespace chars

      dumpmsg.txt

-->

<testlist>
  <test id='pcrcalc258'><msg>
ERROR: 8: argument nr. 1 of function 'spread' is non-spatial only spatial allowed
</msg></test>
<test id='pcrcalc252'><msg>
ERROR: 9: function 'spread' not enough arguments specified
</msg></test>
<test id='pcrcalc252a'>
<!--
  solved bug, there are no arguments
  but arguments are expected
  pos error cannot depend on arguments!
  -->
<msg>
ERROR: 8: function 'maparea' not enough arguments specified
</msg></test>
<test id='pcrcalc253'><msg>
ERROR: 9: function 'spread' too many arguments specified
</msg></test>
<test id='pcrcalc10c'>
  <model>tmp.map=5*inp1b.map;</model>
<msg>
?:1:11:ERROR: inp1b.map: used as scalar type, but has boolean type
</msg></test>
<test id='pcrcalc10b'>
  <!-- map instead of table -->
  <model>tmp.map = lookupnominal(inp1s.map, 5, 8, 10)</model>
  <msg>?:1:25:ERROR: inp1s.map: Expected table, got a map</msg>
</test>
<test id='pcrcalc500'><msg>
ERROR: 8: argument nr. 1 of function 'spread': type is scalar, legal type is one of (nominal,ordinal,boolean)
</msg></test>
<test id='pcrcalc259'><msg>
ERROR: 8: argument nr. 3 of function 'cover': type is boolean, while previous argument types are scalar
</msg></test>
<test id='pcrcalc259a'><msg>
ERROR: 8: argument nr. 2 of function 'cover': type is boolean, while type of argument nr. 1 is scalar
</msg></test>
<test id='pcrcalc260'><msg>
ERROR: 8: right operand of operator 'eq': type is nominal, while type of left argument is boolean
</msg></test>
<test id='pcrcalc260a'>
  <ast>
    <e v='ifthenelse'>
     <p v='inp1b.map'/>
     <e v='nominal' a='4'/>
     <n v='4.3' p='8'/>
   </e>
   </ast><msg>
ERROR: 8: argument nr. 3 of function 'if': type is one of (scalar,directional), while previous argument types are nominal
</msg></test>
 <!-- actulaly we want something else for 501 -->
 <test id='pcrcalc501'><msg>
ERROR: 0: argument nr. 2 of function 'spread': type is one of (nominal,ordinal,boolean), legal type is scalar
</msg></test>
<test id='pcrcalc2a'>
<ast><a v='inp1b.map' p='def2'><n v='2'/></a></ast>
<msg>
def2:ERROR: inp1b.map: defined as boolean type on testTable and redefined here as one of (scalar,nominal,ordinal,ldd,directional) type
</msg></test>
<test id='pcrcalc2'>
<ast>
  <l><a v='tmp.res' p='firstDef'>
        <n v='2'/></a>
     <a v='tmp.res' p='2ndDef'>
        <p v='inp1b.map'/></a>
  </l>
</ast>
<msg>
2ndDef:ERROR: tmp.res: defined as one of (scalar,nominal,ordinal,ldd,directional) type on firstDef and redefined here as boolean type
 </msg></test>
<test id='pcrcalc60'>
 <ast>
  <l>
    <a v='Ch2' p="8"><n v='0'/></a>
   <!--                                  sweep 1    sweep 2  -->
   <a v='SurW' p="7"><e v='scalar' a="0"/></a>
   <!--                                  surw to ns   spatial -->
   <a v='DSt'  p="6"><e v='scalar' a="0"/></a>
   <!--                                  dst to ns    ns     -->
   <a v='DSt0' p="5"><p v='DSt'/></a> <!--     dst0->ns   dst0 still ns! -->
   <a v='DSt'  p="1"><p v='SurW'/></a>
   <a v='DSt'  p="2"><p v='Ch2'/></a>   <!--     dst to ns    dst->spatial -->
   <a v='Ch2'  p="3"><p v='SurW'/></a>
   <a v='SurW' p="4"><e v='spatial' a="0"/></a>
                                  <!--   surw->spatial spatial -->
   <a v='tmp.res'><p v='DSt0'/></a> <!-- report -->
  </l>
 </ast>
 </test>
 <test id='pcrcalc257'>
<ast>
  <e v='timeinput' p='epos'><e v='*' a='1,inp5s.map' /></e>
</ast>
   <msg>
     ERROR: epos: argument nr. 1 of function 'timeinput': type is scalar, legal type is map-stack
 </msg></test>
 <test id='pcrcalc257a'>
<ast>
  <e v='timeinput' p='epos'><e v='*' a='inp5s.map,1' /></e>
</ast>
   <msg>
     ERROR: epos: argument nr. 1 of function 'timeinput': type is scalar, legal type is map-stack
 </msg></test>
 <test id='pcrcalc502'>
<ast>
  <e v='timeinput' p='epos' ><p p="epos" v="inp5s.map"/><n v="1"/></e>
</ast>
   <msg>
ERROR: epos: function 'timeinput' too many arguments specified
 </msg></test>
 <test id='pcrcalc503'>
<ast>
  <e v='timeinput' p='epos' ><p p="epos" v="inp5s.map"/></e>
</ast>
   <msg>
ERROR: epos: argument nr. 1 of function 'timeinput': type is scalar, legal type is map-stack
 </msg></test>
<test id='pcrcalc213b'>
  <model>jan=doesnotexist.map;</model>
  <msg>
?:1:5:ERROR: doesnotexist.map: File 'doesnotexist.map': No such file or directory
 </msg></test>
<test id='pcrcalc11b'>
  <!-- cannot mix these 2 functions -->
  <model>a,b=spread,clump(inp1b.map,0,1)</model>
<msg>
?:1:5:ERROR: Functions 'spread' and 'clump' can not be combined
</msg></test>
<test id='pcrcalc11c'>
  <!-- cannot mix these 2 functions
  they both can mix with other -->
  <model>a,b=spread,lddcreate(inp1b.map,0,1)</model>
<msg>
?:1:5:ERROR: Functions 'spread' and 'lddcreate' can not be combined
</msg></test>
<test id='pcrcalc101'>
 <!-- not enough parameters on left -->
<model>
tmp.map = spread, spreadzone(inp1b.map, 0, 1);
</model>
<msg>
?:1:1:ERROR: function on right side of = does not return the number of parameters defined on left of =
</msg></test>
<test id='pcrcalc43'>
  <model>
binding tmp = 9; tmp = inp1s.map; model tmp.map += 8 ** tmp;</model>
  <msg>
?:1:18:ERROR: 'tmp' is used twice as binding name, first use at line '1:9'
 </msg></test>
 <test id='pcrcalc42'>
   <model>binding tmp = boolean(8); model tmp.map = 3;</model>
   <msg> 
?:1:15:ERROR: Illegal conversion applied: '8' is not a valid 'boolean' value
 </msg></test>
<test id='pcrcalc41'>
  <model>binding tmp = sin(8); model tmp.map = 3;</model>
  <msg>?:1:15:ERROR: function 'sin' illegal here</msg>
</test>
 <test id='pcrcalc43a'>
 <!-- double binding, Ok if first is useless? no better not -->
<model>binding tmp = tmp; tmp = inp1s.map; model tmp.map += 8 ** tmp;</model>
 <msg>
?:1:20:ERROR: 'tmp' is used twice as binding name, first use at line '1:9'
 </msg>
 </test>
 <test id='pcrcalc43b'>
     <model>binding tmp = 9; tmp = 8; model tmp.map = tmp+0;</model>
     <msg>?:1:18:ERROR: 'tmp' is used twice as binding name, first use at line '1:9'</msg>
   </test>
 <test id='pcrcalc238'>
   <model>
timer 1 9 1;
twice = 1..endtime;
twice = 1..endtime;
initial dynamic
report(twice) tmp_s = inp5s.map;
   </model>
  <msg>
?:3:1:ERROR: 'twice' is used twice as report name, first use at line '2:1'
 </msg></test>
<test id='pcrcalc239'>
 <!-- endtime at start of range is parse error -->
   <model>
timer 1 9 1;
reportdefault = endtime..4;
initial dynamic
report tmp_s = inp5s.map;
   </model>
   <msg>?:2:17:ERROR: Syntax error at symbol 'endtime..4'</msg>
</test>
  <test id='pcrcalc242'>
    <model>
timer 1 9 1;
reportdefault = 4+2..2;
initial dynamic
report tmp_s = inp5s.map;
</model>
    <msg>?:2:17:ERROR: report moment contains invalid range '4+2-2'</msg>
  </test>
  <test id='pcrcalc243'>
    <model>
timer 1 9 1;
reportdefault = 4..2;
initial dynamic
report tmp_s = inp5s.map;
    </model>
 <msg>?:2:17:ERROR: report moment contains invalid range '4-2'</msg>
</test>
<test id='pcrcalc244'>
 <!-- catch invalid range insitu -->
  <model>
timer 1 9 1;
initial dynamic
report(4..2) tmp_s = inp5s.map;
</model>
  <msg>?:3:8:ERROR: report moment contains invalid range '4-2'</msg>
</test>
<test id='pcrcalc237'>
<model>
timer 1 9 1;
reportdefault = 1..endtime;
initial dynamic
report(unknown) tmp_s = inp5s.map;
</model>
 <msg>?:4:8:ERROR: 'unknown' is not a report name</msg>
</test>
<test id='pcrcalc255'>
<model>
areamap areaMap255.map;
timer 1 2 1;
initial dynamic
report tmp = boolean(1);
report tmp = boolean(1);
</model>
<msg>?:5:8:ERROR: tmp: Report already done previous (line '4:8')</msg>
</test>
<test id='pcrcalc289'>
  <model>A = dtmsmall.map + inp0s.map;</model>
<msg>
?:1:20:ERROR: inp0s.map: location attributes of 'dtmsmall.map' and 'inp0s.map' are different
</msg></test>
<test id='pcrcalc82'>
  <model options="--clone failureExpected">a=5+sqrt(0.5);</model>
 <msg>--clone:ERROR: failureExpected: File 'failureExpected': No such file or directory</msg>
</test>
<test id='pcrcalc248a'>
<!-- now support non boolean as clone (std. conversion to boolean) 
  -->
  <model options="--clone inp5s.map -d tmp.map">
areamap inp5s.map;
initial
report tmp_s = inp5s.map/spatial(0);
tmp_s2 = tmp_s;
</model>
<msg>
?:3:8:ERROR: RUNTIME -d catched MV creation, inspection map written to tmp.map
</msg>
</test>
<test id='pcrcalc4'>
  <model>model tmp.res = spatial(8.9); tmp.res = xcoordinate(1);</model>
  <msg>ERROR: no clone or area map specified</msg></test>
<test id='pcrcalc5a'>
  <model>timer 1 2 1; initial jan = 8.9; dynamic jan = xcoordinate(1);</model>
  <msg>ERROR: no clone or area map specified</msg>
</test>
<test id='pcrcalc5c'>
  <model>areamap notexist.map; 
    timer 1 2 1; initial jan = 8.9; dynamic jan = xcoordinate(1);</model>
<msg> ?:1:9:ERROR: notexist.map: File 'notexist.map': No such file or directory 
 </msg></test>
<test id='pcrcalc10d'>
 <!-- check if type checking works through binding mapping, and points to binding mapping
   -->
 <model>binding s = boolean(1); model tmp.map = 5 * s;</model>
<msg>?:1:45:ERROR: s: used as scalar type, but has boolean type
</msg>
</test>
<test id='pcrcalc0'>
<model>
  binding tmp.map = 0.2; model report tmp.map = 8 ** inp1s.map;
</model>
<msg>?:1:37:ERROR: tmp.map: Assigning value to constant binding: 'tmp.map=0.2'</msg>
</test>
<test id='pcrcalc69'>
<model>
binding
ntime = 2;
TextureRussia = inp1n.map;
TableRussia=tab69.tbl;
# derived from model form Jitske
# 4 [0.05,0.010> 2
# 4 [0.10,0.50> 3 --> works when
# 4 [0.05,0.10> 2
# 4 [0.10,0.50> 3 

timer
1 2 1;

initial
dynamic
